"""Initial migration with domain, user, and config tables

Revision ID: 877b98c6e048
Revises: 
Create Date: 2025-10-21 00:49:56.622897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877b98c6e048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_name'), 'domain', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_config',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('db_uri', sa.String(length=255), nullable=False),
    sa.Column('db_query', sa.Text(), nullable=False),
    sa.Column('api_auth_type', sa.String(length=50), nullable=False),
    sa.Column('api_username', sa.String(length=255), nullable=False),
    sa.Column('api_password', sa.String(length=255), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=False),
    sa.Column('api_request_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('domain_id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('domain_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'user_id', name='uq_domain_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_user')
    op.drop_table('domain_config')
    op.drop_table('user')
    op.drop_index(op.f('ix_domain_name'), table_name='domain')
    op.drop_table('domain')
    # ### end Alembic commands ###
