"""Add APILog model for request/response logging

Revision ID: 8b80029f58d2
Revises: 877b98c6e048
Create Date: 2025-10-21 01:20:12.733516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b80029f58d2'
down_revision = '877b98c6e048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query_result', sa.Text(), nullable=True),
    sa.Column('query_error', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_url', sa.String(length=255), nullable=False),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_log_domain_id'), 'api_log', ['domain_id'], unique=False)
    op.create_unique_constraint(None, 'domain_config', ['domain_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain_config', type_='unique')
    op.drop_index(op.f('ix_api_log_domain_id'), table_name='api_log')
    op.drop_table('api_log')
    # ### end Alembic commands ###
